Add queryExpression option to MongoDb Source
spring-cloud-stream-app-starters/mongodb pull request #1
Opened 2017-01-10 22:44 UTC by artembilan

Starting with `SI-4.3.6` we can configure query expression in the MongoDb query DSL style.

* Upgrade to `SI-4.3.6`
* Add `MongodbSourceProperties#queryExpression` property, which has a priority over just `query` if configured
* Add test to demonstrate how MongoDb query DSL can be used via a new `queryExpression` property
* Mention a new property in the `README.adoc`
* Resolve deprecations in the tests according Spring Boot upgrade

2017-01-10 22:47 UTC, artembilan commented
M-m-m, I think it would be better to review with `?w=-1`, since there were a lot of indents inconsistency.

2017-01-10 23:23 UTC, artembilan commented on spring-cloud-starter-stream-source-mongodb/src/test/java/org/springframework/cloud/stream/app/mongodb/source/MongodbSourceApplicationTests.java
> +					".with(new org.springframework.data.domain.Sort('greeting'))",
@garyrussell , this `Sort` sample is for discussion.
I would like to include this `org.springframework.data.domain` package to SI by default here in the `MongoDbMessageSource`:
```
//Register MongoDB query API package so FQCN can be avoided in query-expression.
((StandardTypeLocator) typeLocator).registerImport("org.springframework.data.mongodb.core.query");
```
WDYT?

2017-01-11 16:16 UTC, garyrussell requested changes
That's all - yes I agree that we should add that package to the evaluation context within mongo only.

2017-01-11 16:16 UTC, garyrussell commented on spring-cloud-starter-stream-source-mongodb/src/test/java/org/springframework/cloud/stream/app/mongodb/source/MongodbSourceApplicationTests.java
> +							.poll(2, TimeUnit.SECONDS);
We should probably increase these timers to 10 seconds.

2017-01-11 16:16 UTC, garyrussell commented on spring-cloud-starter-stream-source-mongodb/src/test/java/org/springframework/cloud/stream/app/mongodb/source/MongodbSourceApplicationTests.java
> +			assertThat(received, nullValue());
This test seems to be bogus; it's the same as `DefaultTests` but with a long trigger - it seems to be just testing that the trigger doesn't fire within 1 second.

2017-01-11 18:12 UTC, garyrussell approved these changes

2017-01-11 18:12 UTC, garyrussell commented
Merged as e7c50b556a6fa1364f4cec07058fba3c48063edd

2017-01-11 18:12 UTC, closed without merging